### ISSUE TITLE
help

### ISSUE THREAD

**Issue by stepsolar** [averysmalldog/polly#5]
hi, i need your help on how to install your program. I have a raspberry pi4 with grafana and influxdb installed, what should I do to install your program? could you tell me the various steps? Thanks
I don't have Docker
if possible video on youtube thanks

**Comment by averysmalldog** [comment]
@stepsolar closing this as a duplicate, responding in the [tesla-gen3wc-monitor issues page](https://github.com/averysmalldog/tesla-gen3wc-monitor/issues/8)
